driver:
  name: dokken
  chef_version: 12.5.1

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

suites:
  - name: default
    run_list:
      - recipe[yum-centos::default]

  - name: all
    run_list:
      - recipe[yum-centos::default]
    attributes:
      yum:
        contrib:
          managed: true
          enabled: true
        centosplus:
          managed: true
          enabled: true
        fasttrack:
          managed: true
          enabled: true
        cr:
          managed: true
          enabled: true
