settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-7.1
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget

suites:
  - name: default
    run_list:
      - recipe[yum-centos::default]
  - name: all
    run_list:
      - recipe[yum-centos::default]
    attributes:
      yum:
        contrib:
          managed: true
          enabled: true
        centosplus:
          managed: true
          enabled: true
        fasttrack:
          managed: true
          enabled: true
        cr:
          managed: true
          enabled: true
