#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_access_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digitalocean
  driver_config:
    size: 2gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digitalocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: centos-7.0
  driver_plugin: digitalocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list:
  - recipe[yum-centos::default]
  attributes: {}
